pub mod ast;
pub mod type_inference;
pub mod typed_ir;
pub mod untyped_ir;
// pub mod astElem;
// pub mod astElemStmtIf;
// pub mod astElemStmtScope;
// pub mod astType;
// pub mod gen;
// pub mod generator;
// pub mod value;
